# Generated by Django 4.2.4 on 2023-09-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username&email',
        ),
    ]
